# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Spot Me
email: craigaloewen@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Weightlifting - Machine Learning - Physical Therapy
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://spot-me-app.herokuapp.com" # the base hostname & protocol for your site

# Social media profiles - feel free to add more here
github_link:  craigaloewen/spotmecode


# Build settings
markdown: kramdown

gems: ['kramdown']
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']
